const data = [
    ['Blue', 'Green', 'Rust'],
    ['Blue', 'Green', 'Rust'],
    ['Blue', 'Green', 'Rust'],
    ['Brown', 'Rust', 'Black'],
    ['Brown', 'Rust', 'Black'],
    ['Brown', 'Rust', 'Black'],
    ['Chico', 'Rust', 'Brownz'],
    ['Chico', 'Rust', 'Brownz'],
    ['Chico', 'Rust', 'Brownz'],
    ['Brownx', 'Rust', 'Maroon'],
    ['Brownx', 'Rust', 'Maroon'],
    ['Brownx', 'Rust', 'Maroon'],
    ['Brown', 'Green', 'Beige'],
    ['Brown', 'Green', 'Beige'],
    ['Brown', 'Green', 'Beige'],
    ['Marron', 'Black', 'Tan', 'Peach', 'Beige'],
    ['Brown', 'Green', 'Beige'],
    ['Brown', 'Green', 'Beige'],
    ['Brownx', 'Rust', 'Black'],
    ['Gun Metal', 'White', 'Black'],
    ['Pink', 'Black', 'White'],
    ['White', 'Rust', 'Navy Blue'],
    ['Rust', 'Chique', 'Maroon'],
    ['White', 'Black', 'Chique'],
    ['Chico', 'Rust', 'Brownz'],
    ['Brownx', 'Rust', 'Maroon'],
    ['Black', 'Rust', 'Beige'],
    ['Maroon', 'Black', 'Rust'],
    ['Orange', 'Green', 'Yellow'],
    ['Rust', 'Maroon', 'Navy Blue'],
    ['Rust', 'Maroon', 'Navy Blue'],
    ['Beige', 'Navy Blue', 'Rust'],
    ['Navy Blue', 'Chique', 'Brown'],
    ['Navy Blue', 'Rust', 'Brownx'],
    ['Chico', 'Rust', 'Brownz'],
    ['Beige', 'Chico', 'Rust'],
    ['Beige', 'Chico', 'Rust'],
    ['White', 'Rust', 'Navy Blue'],
    ['Black', 'Rust', 'Beige'],
    ['Navy Blue', 'Chique', 'Brown'],
    ['Navy Blue', 'Rust', 'Brownx'],
    ['Maroon', 'Beige', 'Yellow'],
    ['Maroon', 'Beige', 'Yellow'],
    ['Pink', 'Black', 'White'],
    ['Rust', 'O Green', 'Navy Blue'],
    ['Black', 'White', 'Chique'],
    ['Chico', 'Rust', 'Brownz'],
    ['Gun Metal', 'White', 'Black'],
    ['Navy Blue', 'Rust', 'Brownx'],
    ['Navy Blue', 'Rust', 'Beige'],
    ['Olive Green', 'Navy Blue', 'Rust'],
    ['Navy Blue', 'Rust', 'O Green'],
    ['Black', 'Gold', 'Peach'],
    ['Black', 'Gold', 'Peach'],
    ['Maroon', 'Black', 'Rust'],
    ['Navy Blue', 'Rust', 'O Green'],
    ['Brownx', 'Rust', 'Maroon'],
    ['Brownx', 'Rust', 'Maroon'],
    ['Brown', 'Green', 'Beige'],
    ['Rust', 'Chique', 'Maroon'],
    ['Navy Blue', 'Browon', 'Chikoo'],
    ['Navy Blue', 'Chique', 'Brown'],
    ['Navy Blue', 'Rust', 'O Green'],
    ['Beige', 'Chico', 'Rust'],
    ['Black', 'Gold', 'Peach'],
    ['Pink', 'Black', 'White'],
    ['Navy Blue', 'Rust', 'O Green'],
    ['Chique', 'Black', 'White'],
    ['Orange', 'Green', 'Yellow'],
    ['Maroon', 'Black', 'Rust'],
    ['Orange', 'Green', 'Yellow'],
    ['Rust', 'Maroon', 'Navy Blue'],
    ['Rust', 'Chique', 'Maroon'],
    ['Brownx', 'Rust', 'Black'],
    ['Brownx', 'Rust', 'Black'],
    ['Gun Metal', 'White', 'Black'],
    ['White', 'Rust', 'Navy Blue'],
    ['Black', 'Rust', 'Beige'],
    ['Beige', 'Navy Blue', 'Rust'],
    ['Maroon', 'Beige', 'Yellow'],
    ['Maroon', 'Begie', 'Rust'],
    ['Maroon', 'Black', 'Begie'],
    ['Navy Blue', 'Rust', 'Maroon'],
    ['Brownz', 'Rust', 'Navy Blue'],
    ['Rust', 'Black', 'Chikoo'],
    ['Maroon', 'Begie', 'O Green'],
    ['Browon', 'Chikoo', 'Navy Blue'],
    ['Black', 'Blue', 'Peach'],
    ['Green', 'Peach', 'Gray'],
    ['Navy Blue', 'Chikoo', 'Begie'],
    ['Navy Blue', 'Browon', 'Chikoo'],
    ['Blue', 'Black', 'Beige'],
    ['Beige', 'Pista', 'Black'],
    ['Pista', 'Begie', 'Peach'],
    ['Black', 'Blue', 'Peach'],
    ['Maroon', 'Black', 'Tan', 'Peach', 'Beige'],
    ['Beige', 'Maroon', 'Chique'],
    ['Navy Blue', 'NT/BTT', 'Olive Green'],
    ['Begie', 'Rust', 'Navy Blue'],
    ['Begie', 'Maroon', 'Navy Blue'],
    ['Begie', 'Maroon', 'Navy Blue'],
    ['Navy Blue', 'Browon', 'Chikoo'],
    ['Navy Blue', 'NT/BTT', 'Olive Green'],
    ['Begie', 'Rust', 'Navy Blue'],
    ['T Blue', 'Maroon', 'Orange'],
    ['Rust', 'Maroon', 'Begie'],
    ['Pista', 'Begie', 'Peach'],
    ['Grey', 'Musturd', 'Blue'],
    ['Maroon', 'Black', 'Tan', 'Peach', 'Beige'],
    ['Maroon', 'Brownz', 'Rust'],
    ['Maroon', 'Brownz', 'Rust'],
    ['Mango Yellow', 'Light Gray', 'Chique'],
    ['Gold', 'Sultan', 'Silver'],
    ['Black', 'Pista', 'Beige'],
    ['Maroon', 'Black', 'Begie'],
    ['Rust', 'Navy Blue', 'Begie'],
    ['Rust', 'Navy Blue', 'Begie'],
    ['Rust', 'Navy Blue', 'Begie'],
    ['Pista', 'Begie', 'Peach'],
    ['Beige', 'Pista', 'Black'],
    ['Black', 'Pista', 'Beige'],
    ['Rust', 'Maroon', 'Begie'],
    ['Maroon', 'Begie', 'Rust'],
    ['Navy Blue', 'Browon', 'Chikoo'],
    ['Brown', 'Black'],
    ['Beige', 'Green', 'Black', 'Peach'],
    ['Grey', 'Musturd', 'Blue'],
    ['Black', 'Pista', 'Beige'],
    ['T Blue', 'Maroon', 'Orange'],
    ['Maroon', 'Begie', 'O Green'],
    ['Beige', 'Green', 'Black', 'Peach'],
    ['Green', 'Peach', 'Gray'],
    ['Maroon', 'Begie', 'Rust'],
    ['Maroon', 'Black', 'Tan', 'Peach', 'Beige'],
    ['Navy Blue', 'NT/BTT', 'Olive Green'],
    ['Beige', 'Maroon', 'Chique'],
    ['Navy Blue', 'Rust', 'Maroon'],
    ['Rust', 'Black', 'Chikoo'],
    ['Navy Blue', 'Chikoo', 'Begie'],
    ['Gold', 'Sultan', 'Silver'],
    ['Beige', 'Pista', 'Black'],
    ['Black', 'Blue', 'Peach'],
    ['Navy Blue', 'Rust', 'Maroon'],
    ['Navy Blue', 'Browon', 'Chikoo'],
    ['Blue', 'Black', 'Beige'],
    ['Green', 'Peach', 'Gray'],
    ['Begie', 'Rust', 'Navy Blue'],
    ['Beige', 'Maroon', 'Chique'],
    ['Begie', 'Maroon', 'Navy Blue'],
    ['Rust', 'Navy Blue', 'Begie'],
    ['Gold', 'Sultan', 'Silver'],
    ['Beige', 'Green', 'Black', 'Peach'],
    ['Rust', 'Maroon', 'Begie'],
    ['Browon', 'Chikoo', 'Navy Blue'],
    ['Navy Blue', 'Chikoo', 'Begie'],
    ['Blue', 'Black', 'Beige'],
    ['Beige', 'Green', 'Black', 'Peach'],
    ['Grey', 'Musturd', 'Blue'],
    ['Maroon', 'Brownz', 'Rust'],
    ['T Blue', 'Maroon', 'Orange'],
    ['Rust', 'Black', 'Chikoo'],
    ['Brownz', 'Rust', 'Navy Blue'],
    ['Maroon', 'Black', 'Tan', 'Peach', 'Beige'],
    ['Navy Blue', 'Browon', 'Chikoo'],
    ['Maroon', 'Black', 'Begie'],
    ['Mango Yellow', 'Light Gray', 'Chique'],
    ['Mango Yellow', 'Light Gray', 'Chique'],
    ['Browon', 'Chikoo', 'Navy Blue'],
    ['Brown', 'Black'],
    ['Maroon', 'Black', 'Tan', 'Peach', 'Beige'],
    ['Tan', 'Peach', 'Beige'],
    ['Tan', 'Peach', 'Beige'],
    ['Tan', 'Peach', 'Beige'],
    ['Black', 'Tan', 'Marron'],
    ['Black', 'Tan', 'Marron'],
    ['Marron', 'Black', 'Tan'],
    ['Peach', 'White', 'Beige', 'Black', 'Green'],
    ['Peach', 'White', 'Beige', 'Black', 'Green'],
    ['Peach', 'White', 'Beige', 'Black', 'Green'],
    ['Peach', 'White', 'Beige', 'Black', 'Green'],
    ['Peach', 'White', 'Beige', 'Black', 'Green'],
    ['Black', 'Gun Metal', 'Sultan'],
    ['Gun Metal', 'Black', 'Sultan'],
    ['Black', 'Gun Metal', 'Sultan'],
    ['Blue', 'Black', 'Tan'],
    ['Black', 'Blue', 'Tan'],
    ['Blue', 'Black', 'Tan'],
    ['Maroon', 'Black', 'Sultan'],
    ['Marron', 'Sultan', 'Black'],
    ['Black', 'Sultan', 'Marron'],
    ['Green', 'Yellow', 'Peach'],
    ['Yellow', 'Green', 'Peach'],
    ['Green', 'Yellow', 'Peach'],
    ['Green', 'Yellow', 'Peach'],
    ['Yellow', 'Green', 'Peach'],
    ['Green', 'Yellow', 'Peach'],
    ['Black', 'Gray', 'Peach'],
    ['Black', 'Grey', 'Peach'],
    ['Black', 'Peach', 'Gray'],
    ['Peach', 'Tan', 'Black'],
    ['Peach', 'Tan', 'Black'],
    ['Peach', 'Black', 'Tan'],
    ['LightBlue', 'Blue', 'Grey'],
    ['LightBlue', 'Blue', 'Grey'],
    ['LightBlue', 'Blue', 'Grey'],
    ['Gold', 'Silver', 'Peach'],
    ['Gold', 'Silver', 'Peach'],
    ['Gold', 'Silver', 'Peach'],
    ['Lavendor', 'Peach', 'Gray'],
    ['Peach', 'Lavendor', 'Gray'],
    ['Lavendor', 'Peach', 'Grey'],
    ['Peach', 'Orange'],
    ['Peach', 'Orange'],
    ['Yellow', 'Green', 'White', 'Black', 'Beige'],
    ['Dark Blue', 'Black', 'Maroon'],
    ['Cream', 'Peach', 'Black'],
    ['Yellow', 'Green', 'White', 'Black', 'Beige'],
    ['Antique', 'Gold'],
    ['Sultan', 'Gold'],
    ['Black', 'Yellow', 'Antique', 'Peach'],
    ['White', 'Peach', 'Black'],
    ['Gun Metal', 'Gold', 'Sultan'],
    ['White', 'Black', 'Beige'],
    ['Cream', 'Peach', 'Black'],
    ['Gun Metal', 'Gold', 'Sultan'],
    ['Black', 'Yellow', 'Antique', 'Peach'],
    ['White', 'Black', 'Beige'],
    ['Gold', 'Black', 'Antique'],
    ['Black', 'Beige', 'Tan'],
    ['Gold', 'Antique'],
    ['Sultan', 'Gold'],
    ['Black', 'Yellow', 'Antique', 'Peach'],
    ['Antique', 'Black'],
    ['Black', 'Peach', 'Cream'],
    ['Yellow', 'Gold', 'Pista Green'],
    ['Sultan', 'Red'],
    ['Sultan', 'Gold'],
    ['White', 'Peach', 'Tan'],
    ['Antique', 'Black'],
    ['White', 'Black', 'Beige'],
    ['Cream', 'Peach', 'Black'],
    ['Cream', 'Peach', 'Black'],
    ['Yellow', 'Gold', 'Pista Green'],
    ['Black', 'Tan', 'Maroon'],
    ['Gold', 'Black', 'Antique'],
    ['Peach', 'Tan', 'White'],
    ['Tan', 'White', 'Peach'],
    ['Black', 'Tan', 'Maroon'],
    ['Dark Blue', 'Black', 'Maroon'],
    ['Dark Blue', 'Black', 'Maroon'],
    ['Black', 'Beige', 'Tan'],
    ['Cream', 'Peach', 'Black'],
    ['Cream', 'Peach', 'Black'],
    ['Antique', 'Gold'],
    ['Sultan', 'Red'],
    ['Sultan', 'Silver'],
    ['Cream', 'Peach', 'Black'],
    ['Sultan', 'Gold'],
    ['Black', 'Yellow', 'Antique', 'Peach'],
    ['Yellow', 'Green', 'White', 'Black', 'Beige'],
    ['Yellow', 'Green', 'White', 'Black', 'Beige'],
    ['Yellow', 'Green', 'White', 'Black', 'Beige'],
    ['Black', 'Beige', 'Tan'],
    ['Black', 'Peach', 'Cream'],
    ['Black', 'Peach', 'Cream'],
    ['White', 'peach', 'Black'],
    ['Gold', 'Black', 'Antique'],
    ['Cream', 'Peach', 'Black'],
    ['Black', 'Tan', 'Maroon'],
    ['White', 'peach', 'Black'],
    ['Gun Metal', 'Gold', 'Sultan'],
    ['Cream', 'Peach', 'Black'],
    ['Yellow', 'Gold', 'Pista Green'],
    ['Sultan', 'Gold'],
    ['Antique', 'Gold'],
    ['Sultan', 'Gold'],
    ['Sultan', 'Silver'],
    ['Red', 'Gold'],
    ['Cream', 'Peach', 'Black', 'White'],
    ['Green', 'Peach', 'Black', 'Gray'],
    ['Red', 'Gold'],
    ['Cream', 'Black', 'Green', 'Peach'],
    ['Green', 'Peach', 'Black', 'Gray'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Cream', 'Black', 'Blue', 'Peach'],
    ['Cream', 'Black', 'Blue', 'Peach'],
    ['Cream', 'Black', 'Green', 'Peach'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['Gray', 'Black', 'Cream', 'Yellow'],
    ['Gray', 'Black', 'Sultan', 'Antique'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['Cream', 'Black', 'Blue', 'Peach'],
    ['White', 'Black', 'Peach', 'Tan'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['White', 'Black', 'Peach', 'Tan'],
    ['Tan', 'Black', 'Peach', 'White'],
    ['Gray', 'Black', 'White'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Gray', 'Black', 'Sultan', 'Antique'],
    ['Cream', 'Black', 'Gray', 'Peach'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['Gray', 'Black', 'Cream', 'Yellow'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Gray', 'Black', 'Cream', 'Yellow'],
    ['Green', 'Peach', 'Black', 'Gray'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Green', 'Peach', 'Black', 'Gray'],
    ['Peach', 'Black', 'Cream', 'White'],
    ['Cream', 'Black', 'Blue', 'Peach'],
    ['White', 'Black', 'Peach', 'Tan'],
    ['Gray', 'Black', 'Cream', 'Yellow'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['Cream', 'Black', 'Green', 'Peach'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Peach', 'Black', 'Cream', 'White'],
    ['White', 'Black', 'Peach', 'Tan'],
    ['Cream', 'Black', 'Gray', 'Peach'],
    ['Gray', 'Black', 'Sultan', 'Antique'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Cream', 'Black', 'Blue', 'Peach'],
    ['Gray', 'Black', 'White'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Gray', 'Black', 'Cream', 'Yellow'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Gray', 'Black', 'Cream', 'Yellow'],
    ['Cream', 'Black', 'Green', 'Peach'],
    ['Green', 'Peach', 'Black', 'Gray'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['White', 'Black', 'Peach', 'Tan'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['Cream', 'Black', 'Gray', 'Peach'],
    ['White', 'Black', 'Peach', 'Tan'],
    ['Peach', 'Black', 'Cream', 'White'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Gray', 'Black', 'Cream', 'Yellow'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Green', 'Peach', 'Black', 'Gray'],
    ['Gray', 'Black', 'Sultan', 'Antique'],
    ['Cream', 'Black', 'Blue', 'Peach'],
    ['Gray', 'Black', 'White'],
    ['Gray', 'Black', 'Cream', 'Yellow'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Cream', 'Black', 'Green', 'Peach'],
    ['Peach', 'Black', 'Cream', 'White'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Gray', 'Black', 'Cream', 'Yellow'],
    ['White', 'Black', 'Peach', 'Tan'],
    ['Green', 'Peach', 'Black', 'Gray'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['White', 'Black', 'Peach', 'Tan'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['Cream', 'Black', 'Gray', 'Peach'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Gray', 'Black', 'Sultan', 'Antique'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['Cream', 'Black', 'Blue', 'Peach'],
    ['Gray', 'Black', 'White'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Gray', 'Black', 'Cream', 'Yellow'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Green', 'Peach', 'Black', 'Gray'],
    ['Cream', 'Black', 'Green', 'Peach'],
    ['Peach', 'Black', 'Cream', 'White'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['White', 'Black', 'Peach', 'Tan'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Gray', 'Black', 'Cream', 'Yellow'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Gray', 'Black', 'Sultan', 'Antique'],
    ['Cream', 'Black', 'Blue', 'Peach'],
    ['Gray', 'Black', 'White'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['Cream', 'Black', 'Gray', 'Peach'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Gray', 'Black', 'Cream', 'Yellow'],
    ['Cream', 'Black', 'Green', 'Peach'],
    ['Green', 'Peach', 'Black', 'Gray'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['White', 'Black', 'Peach', 'Tan'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Peach', 'Black', 'Cream', 'White'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['Gray', 'Black', 'Cream', 'Yellow'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Cream', 'Black', 'Blue', 'Peach'],
    ['Gray', 'Black', 'White'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Green', 'Peach', 'Black', 'Gray'],
    ['Cream', 'Black', 'Green', 'Peach'],
    ['Peach', 'Black', 'Cream', 'White'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['White', 'Black', 'Peach', 'Tan'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Peach', 'Black', 'Cream', 'White'],
    ['Gray', 'Black', 'Cream', 'Yellow'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Cream', 'Black', 'Blue', 'Peach'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Green', 'Peach', 'Black', 'Gray'],
    ['Cream', 'Black', 'Green', 'Peach'],
    ['Peach', 'Black', 'Cream', 'White'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['White', 'Black', 'Peach', 'Tan'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Cream', 'Black', 'Gray', 'Peach'],
    ['Gray', 'Black', 'Cream', 'Yellow'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Peach', 'Black', 'Cream', 'White'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Green', 'Peach', 'Black', 'Gray'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Cream', 'Black', 'Green', 'Peach'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['White', 'Black', 'Peach', 'Tan'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Gray', 'Black', 'Cream', 'Yellow'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Gray', 'Black', 'Sultan', 'Antique'],
    ['Peach', 'Black', 'Cream', 'White'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['Cream', 'Black', 'Gray', 'Peach'],
    ['White', 'Black', 'Peach', 'Tan'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['Cream', 'Black', 'Blue', 'Peach'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Green', 'Peach', 'Black', 'Gray'],
    ['Cream', 'Black', 'Green', 'Peach'],
    ['Cream', 'Black', 'Gray', 'Peach'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Cream', 'Black', 'Green', 'Peach'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['White', 'Black', 'Peach', 'Tan'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Peach', 'Black', 'Cream', 'White'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['Gray', 'Black', 'Cream', 'Yellow'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Cream', 'Black', 'Gray', 'Peach'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['Cream', 'Black', 'Blue', 'Peach'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Green', 'Peach', 'Black', 'Gray'],
    ['Cream', 'Black', 'Green', 'Peach'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Cream', 'Black', 'Green', 'Peach'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['White', 'Black', 'Peach', 'Tan'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Gray', 'Black', 'Cream', 'Yellow'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Gray', 'Black', 'Sultan', 'Antique'],
    ['Peach', 'Black', 'Cream', 'White'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['Cream', 'Black', 'Gray', 'Peach'],
    ['White', 'Black', 'Peach', 'Tan'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['Cream', 'Black', 'Blue', 'Peach'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Green', 'Peach', 'Black', 'Gray'],
    ['Cream', 'Black', 'Green', 'Peach'],
    ['Cream', 'Black', 'Gray', 'Peach'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Cream', 'Black', 'Green', 'Peach'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['White', 'Black', 'Peach', 'Tan'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Peach', 'Black', 'Cream', 'White'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['Gray', 'Black', 'Cream', 'Yellow'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Cream', 'Black', 'Gray', 'Peach'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['Cream', 'Black', 'Blue', 'Peach'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Green', 'Peach', 'Black', 'Gray'],
    ['Cream', 'Black', 'Green', 'Peach'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Cream', 'Black', 'Green', 'Peach'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['White', 'Black', 'Peach', 'Tan'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Gray', 'Black', 'Cream', 'Yellow'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Gray', 'Black', 'Sultan', 'Antique'],
    ['Peach', 'Black', 'Cream', 'White'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['Cream', 'Black', 'Gray', 'Peach'],
    ['White', 'Black', 'Peach', 'Tan'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['Cream', 'Black', 'Blue', 'Peach'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Green', 'Peach', 'Black', 'Gray'],
    ['Cream', 'Black', 'Green', 'Peach'],
    ['Cream', 'Black', 'Gray', 'Peach'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Cream', 'Black', 'Green', 'Peach'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['White', 'Black', 'Peach', 'Tan'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Peach', 'Black', 'Cream', 'White'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['Gray', 'Black', 'Cream', 'Yellow'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Cream', 'Black', 'Gray', 'Peach'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['Cream', 'Black', 'Blue', 'Peach'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Green', 'Peach', 'Black', 'Gray'],
    ['Cream', 'Black', 'Green', 'Peach'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Cream', 'Black', 'Green', 'Peach'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['White', 'Black', 'Peach', 'Tan'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Gray', 'Black', 'Cream', 'Yellow'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Gray', 'Black', 'Sultan', 'Antique'],
    ['Peach', 'Black', 'Cream', 'White'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['Cream', 'Black', 'Gray', 'Peach'],
    ['White', 'Black', 'Peach', 'Tan'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['Cream', 'Black', 'Blue', 'Peach'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Green', 'Peach', 'Black', 'Gray'],
    ['Cream', 'Black', 'Green', 'Peach'],
    ['Cream', 'Black', 'Gray', 'Peach'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Cream', 'Black', 'Green', 'Peach'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['White', 'Black', 'Peach', 'Tan'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Peach', 'Black', 'Cream', 'White'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['Gray', 'Black', 'Cream', 'Yellow'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Cream', 'Black', 'Gray', 'Peach'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['Cream', 'Black', 'Blue', 'Peach'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Green', 'Peach', 'Black', 'Gray'],
    ['Cream', 'Black', 'Green', 'Peach'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Cream', 'Black', 'Green', 'Peach'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['White', 'Black', 'Peach', 'Tan'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Gray', 'Black', 'Cream', 'Yellow'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Gray', 'Black', 'Sultan', 'Antique'],
    ['Peach', 'Black', 'Cream', 'White'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['Cream', 'Black', 'Gray', 'Peach'],
    ['White', 'Black', 'Peach', 'Tan'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['Cream', 'Black', 'Blue', 'Peach'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Green', 'Peach', 'Black', 'Gray'],
    ['Cream', 'Black', 'Green', 'Peach'],
    ['Cream', 'Black', 'Gray', 'Peach'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Cream', 'Black', 'Green', 'Peach'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['Black', 'Cream', 'Purple', 'Peach'],
    ['White', 'Black', 'Peach', 'Tan'],
    ['Black', 'Gray', 'Silver', 'Chikoo'],
    ['Cream', 'Black', 'Tan', 'Green'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
    ['Peach', 'Black', 'Cream', 'White'],
    ['Black', 'Peach', 'Purple', 'Cream'],
    ['Gray', 'Black', 'Cream', 'Yellow'],
    ['Peach', 'Black', 'Chikoo', 'Cream'],
   
]

const getallUniqueColor = async (data) => {
    let uniqueColors = new Set();

    data.forEach((item) => {
        item.forEach((color) => {
            uniqueColors.add(color);
        });
    });

    return Array.from(uniqueColors);
};

// Example usage
getallUniqueColor(data).then((uniqueColors) => {
  
});

getallUniqueColor(data);